kind: Job
apiVersion: batch/v1
metadata:
  name: v11y-walker-cve-2022
  labels:
    app.kubernetes.io/component: v11y
    app.kubernetes.io/instance: redhat-trusted-profile-analyzer
    app.kubernetes.io/name: v11y-walker
    app.kubernetes.io/part-of: trusted-profile-analyzer
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      labels:
        app.kubernetes.io/component: v11y
        app.kubernetes.io/instance: redhat-trusted-profile-analyzer
        app.kubernetes.io/name: v11y-walker
    spec:
      volumes:
        - name: cvelist
          persistentVolumeClaim:
            claimName: v11y-walker
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: git-fetch
          command:
            - /bin/sh
          imagePullPolicy: Always
          volumeMounts:
            - name: cvelist
              mountPath: /git
          terminationMessagePolicy: File
          image: 'registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel9@sha256:9142fe58fad28a8b469b17bdd84fe6bbcb6830811a3b31c671142ce109739455'
          workingDir: /git
          args:
            - '-ec'
            - |
              if test -d cvelistV5; then
                cd cvelistV5
                git pull
              else
                git clone https://github.com/CVEProject/cvelistV5
              fi
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9010
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: walker
          command:
            - /trust
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9010
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: RUST_LOG
              value: info
            - name: INFRASTRUCTURE_ENABLED
              value: 'true'
            - name: INFRASTRUCTURE_BIND
              value: '[::]:9010'
            - name: STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: user
            - name: STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: password
            - name: STORAGE_ENDPOINT
              value: 'http://minio:9000'
            - name: STORAGE_REGION
              value: eu-west-1
            - name: STORAGE_BUCKET
              value: v11y-default
          ports:
            - name: infra
              containerPort: 9010
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: cvelist
              mountPath: /mnt
          terminationMessagePolicy: File
          image: 'registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel9@sha256:9142fe58fad28a8b469b17bdd84fe6bbcb6830811a3b31c671142ce109739455'
          args:
            - v11y
            - walker
            - '--source'
            - /mnt/cvelistV5
            - '--prefix'
            - CVE-2022-
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false