apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-monitor
rules:
  - verbs:
      - create
      - get
      - delete
    apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
