- name: Check Pipelines Subscription
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: openshift-pipelines-operator
        namespace: openshift-operators
      spec:
        installPlanApproval: Automatic
        channel: latest
        name: openshift-pipelines-operator-rh
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait Tekton Operator
  kubernetes.core.k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: v1
    kind: Pod
    namespace: openshift-operators
    label_selectors:
      - app = tekton-operator
    field_selectors:
      - status.phase=Running
  register: r_tekton_pod
  retries: 20
  delay: 10
  until: r_tekton_pod.resources | list | length == 1
