- name: Evaluate DevSpaces Subscription (devworkspace-operator)
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    definition:
      metadata:
        name: devworkspace-operator
        namespace: openshift-operators
      spec:
        channel: fast
        installPlanApproval: Automatic
        name: devworkspace-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Evaluate DevSpaces Subscription (devspaces)
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    definition:
      metadata:
        name: devspaces
        namespace: openshift-operators
      spec:
        channel: stable
        installPlanApproval: Automatic
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        name: devspaces

- name: Wait DevSpaces Operator To Be Running
  kubernetes.core.k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: v1
    kind: Pod
    namespace: openshift-operators
    label_selectors:
      - app = devspaces-operator
      - app.kubernetes.io/component = devspaces-operator
    field_selectors:
      - status.phase=Running
  register: r_devspace_pod
  retries: 120
  delay: 10
  until: r_devspace_pod.resources | list | length == 1

- name: Check Devspaces namespace
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: v1
    kind: Namespace
    name: openshift-devspaces
    state: present
  register: _namespace
  retries: 10
  delay: 5
  until:
    - _namespace is succeeded

- name: Check Che Cluster
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    state: present
    namespace: openshift-devspaces
    resource_definition: "{{ lookup('file', 'devspace-cluster.yml') }}"
  register: _che
  retries: 10
  delay: 10
  until: not _che.failed

- name: Wait DevSpaces Instance To Be Running
  kubernetes.core.k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: v1
    kind: Pod
    namespace: openshift-devspaces
    label_selectors:
      - app = devspaces
      - component = che-gateway
    field_selectors:
      - status.phase=Running
  register: r_devspace_pod
  retries: 120
  delay: 10
  until: r_devspace_pod.resources | list | length == 1
