- name: Evaluate Keycloak Realms
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ keycloak_project }}'
    resource_definition: "{{ lookup('template', item) }}"
  loop:
    - rhdh-realm.yml.j2
    - tas-realm.yml.j2
