kind: ConfigMap
apiVersion: v1
metadata:
  name: backstage-dynamic-plugins-developer-hub
  labels:
    app.kubernetes.io/instance: developer-hub
    app.kubernetes.io/name: backstage
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic
        disabled: false