- name: Evaluate Namespace {{ tpa_project }}
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: v1
    kind: Namespace
    name: '{{ tpa_project }}'
    state: present

- name: Include Minio
  ansible.builtin.include_role:
    name: minio

- name: Include Streams
  ansible.builtin.include_role:
    name: streams

- name: Evaluate Postgresdb instance
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ tpa_project }}'
    resource_definition: "{{ lookup('file', 'postgresdb.yml') }}"

- name: Waiting for Postgresdb instance to be running
  kubernetes.core.k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: v1
    kind: Pod
    namespace: '{{ tpa_project }}'
    label_selectors:
      - app = postgresql-db
      - statefulset.kubernetes.io/pod-name = postgresql-db-0
    field_selectors:
      - status.phase=Running
  register: r_minio_pod
  retries: 20
  delay: 10
  until: r_minio_pod.resources | list | length == 1

- name: Evaluate Secrets
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ tpa_project }}'
    resource_definition: "{{ lookup('template', 'secrets.yml.j2') }}"

- name: Create values for Helm deployment
  ansible.builtin.copy:
    content: "{{ lookup('template', 'values-rhtpa.yaml.j2') }}"
    dest: "/tmp/values-rhtpa.yaml"
    mode: "0655"

# - name: Add openshift-helm-charts chart repo
#   kubernetes.core.helm_repository:
#     name: openshift-helm-charts
#     repo_url: "https://charts.openshift.io"
#   ignore_errors: true
#   register: ignore_errors_register

# - name: Deploy redhat-trusted-profile-analyzer chart
#   kubernetes.core.helm:
#     api_key: '{{ token }}'
#     host: '{{ server }}'
#     validate_certs: false
#     name: redhat-trusted-profile-analyzer
#     chart_ref: openshift-helm-charts/redhat-trusted-profile-analyzer
#     chart_version: '0.1.1'
#     release_namespace: '{{ tpa_project }}'
#     update_repo_cache: false
#     values: "{{ lookup('template', 'values-rhtpa.yaml.j2') | from_yaml }}"
