- name: Check Required Parameters - aws_ec2_access_key
  ansible.builtin.fail:
    msg: "This playbook requires 'aws_ec2_access_key' to be defined"
  when:
    - (aws_ec2_access_key is undefined)  or (aws_ec2_access_key | length == 0)
  ignore_errors: false

- name: Check Required Parameters - aws_ec2_secret_key
  ansible.builtin.fail:
    msg: "This playbook requires 'aws_ec2_secret_key' to be defined"
  when:
    - (aws_ec2_secret_key is undefined)  or (aws_ec2_secret_key | length == 0)
  ignore_errors: false

- name: Set Bucket Name
  ansible.builtin.set_fact:
    s3_bucket_name: "trustify-{{ lookup('community.general.random_string', special=false, upper=false) }}"

- name: Print Bucket Name
  ansible.builtin.debug:
    var: s3_bucket_name

- name: Evaluate Namespace {{ tpa_project }}
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: v1
    kind: Namespace
    name: '{{ tpa_project }}'
    state: present

- name: Evaluate OperatorGroup {{ tpa_project }}
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: operators.coreos.com/v1
    kind: OperatorGroup
    definition:
      metadata:
        name: '{{ tpa_project }}-group'
        namespace: '{{ tpa_project }}'
      spec:
        targetNamespaces:
          - '{{ tpa_project }}'

- name: Check TPA Subscription
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: rhtpa-operator
        namespace: '{{ tpa_project }}'
      spec:
        channel: stable-v1.1
        name: rhtpa-operator
        installPlanApproval: Automatic
        source: redhat-operators
        sourceNamespace: openshift-marketplace

# currently Rust AWS S3 SDK does not work with Minio
# - name: Include Minio
#   ansible.builtin.include_role:
#     name: minio

- name: Check S3 bucket
  amazon.aws.s3_bucket:
    aws_access_key: "{{ aws_ec2_access_key }}"
    aws_secret_key: "{{ aws_ec2_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ s3_bucket_name }}"
    state: present

- name: Evaluate Postgresdb instance
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ tpa_project }}'
    resource_definition: "{{ lookup('template', 'postgresdb.yml.j2') }}"

- name: Waiting for Postgresdb instance to be running
  kubernetes.core.k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    api_version: v1
    kind: Pod
    namespace: '{{ tpa_project }}'
    label_selectors:
      - app = postgresql-db
      - statefulset.kubernetes.io/pod-name = postgresql-db-0
    field_selectors:
      - status.phase=Running
  register: r_minio_pod
  retries: 20
  delay: 10
  until: r_minio_pod.resources | list | length == 1

- name: Evaluate Secrets
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ tpa_project }}'
    resource_definition: "{{ lookup('template', 'secrets.yml.j2') }}"

- name: Evaluate TPA Instance
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: '{{ tpa_project }}'
    resource_definition: "{{ lookup('template', 'tpa.yml.j2') }}"
