- name: Evaluate TAS Subscription
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: rhtas-operator
        namespace: openshift-operators
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: rhtas-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait for TAS CRDs
  kubernetes.core.k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: securesigns.rhtas.redhat.com
  register: crd_securesigns
  until: crd_securesigns.resources | list | length == 1
  retries: 10
  delay: 30

- name: Wait for TAS project
  kubernetes.core.k8s_info:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: '{{ verify_tls }}'
    api_version: project.openshift.io/v1
    kind: Project
    name: trusted-artifact-signer
  register: tas_project
  until: tas_project.resources | list | length == 1
  retries: 10
  delay: 30

- name: Evaluate Securesign instance
  kubernetes.core.k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: false
    state: present
    namespace: 'trusted-artifact-signer'
    resource_definition: "{{ lookup('template', 'securesign.yml.j2') }}"
