apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: local-cluster
spec:
  clusterName: local-cluster
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints