rhdh_sa_name: local-cluster
rhdh_secret_name: secrets-rhdh
rhdh_cm_name: app-config-rhdh
rhdh_template_urls:
  # - https://github.com/GcBackstageDemos/tssc-sample-templates/blob/my-version/all.yaml
  # - https://github.com/GcBackstageDemos/trusted-application-pipeline-templates/blob/my-version/showcase-templates.yaml
  - https://github.com/GcBackstageDemos/backstage-camel-templates/blob/main/templates.yaml
