- name: Install Trusted Application Pipeline
  hosts: localhost
  vars:
    verify_tls: false
    insecure_skip_tls_verify: true

    keycloak_project: keycloak-system
    keycloak_tas_realm_name: trusted-artifact-signer
    keycloak_user_username: admin
    keycloak_user_password: password

    kafka_project: '{{ tpa_project }}'
    kafka_user_name: tester
    kafka_bootstrap_host: cluster-kafka-bootstrap
# TAS Configuratio
    tas_channel: stable-v1.1
# TPA configuration
    tpa_project: trusted-profile-analyzer
    tpa_cli_secret: walker_secret
    tpa_helm_version: 1.0.2
    tpa_db_storage_size: 40Gi

# Minio configuration
    minio_project: '{{ tpa_project }}'
    minio_key: minio
    minio_secret: minio123
    aws_region: us-east-2

# Developer Hub Configuration
    rhdh_project: rhdh
    rhdh_keycloak_realm: rhdh
    rhdh_keycloak_client_id: rhdh
    rhdh_keycloak_client_secret: 9IAuKgbRcEUTU4mjeUUTY25P6IKo0B6L
    rhdh_sa_name: local-cluster
    rhdh_secret_name: secrets-rhdh
    rhdh_cm_name: app-config-rhdh
    rhdh_ns: rhdh
    rhdh_template_urls:
      # - https://github.com/GcBackstageDemos/tssc-sample-templates/blob/my-version/all.yaml
      # - https://github.com/GcBackstageDemos/trusted-application-pipeline-templates/blob/my-version/showcase-templates.yaml
      - https://github.com/GcBackstageDemos/backstage-camel-templates/blob/main/templates.yaml

  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This play requires 'server' and 'token' to be defined"
      when:
        - (server is not defined) or (token is not defined) or (server is none) or (token is none)
      ignore_errors: false
      tags: [keycloak, acs, tekton, argocd, tas, tpa, devhub, devspaces]

    - name: Set domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"
      tags: [keycloak, acs, tekton, argocd, tas, tpa, devhub, devspaces]

    - name: Set Subdomain
      ansible.builtin.set_fact:
        route_subdomain: "apps.{{ domain }}"
      tags: [keycloak, acs, tekton, argocd, tas, tpa, devhub, devspaces]

    - name: Include Keycloak
      ansible.builtin.include_role:
        name: keycloak
        apply:
          tags: [keycloak, tas, tpa, devhub]
      tags: [keycloak, tas, tpa, devhub]

    - name: Include ACS
      ansible.builtin.include_role:
        name: acs
        apply:
          tags: acs
      tags: acs

    - name: Include Tekton
      ansible.builtin.include_role:
        name: tekton
        apply:
          tags: [tekton, devhub]
      tags: [tekton, devhub]

    - name: Include ArgoCD
      ansible.builtin.include_role:
        name: argocd
        apply:
          tags: [argocd, devhub]
      tags: [argocd, devhub]

    - name: Include TAS
      ansible.builtin.include_role:
        name: tas
        apply:
          tags: tas
      tags: tas

    - name: Include TPA
      ansible.builtin.include_role:
        name: tpa
        apply:
          tags: tpa
      tags: tpa

    - name: Include RHDH
      ansible.builtin.include_role:
        name: devhub
        apply:
          tags: devhub
      tags: devhub

    - name: Include DevSpaces
      ansible.builtin.include_role:
        name: devspaces
        apply:
          tags: devspaces
      tags: devspaces
