- name: Install Trusted Application Pipeline
  hosts: localhost
  vars:
    delete_demo: false
    verify_tls: false
    insecure_skip_tls_verify: true

    keycloak_project: keycloak-system
    keycloak_tas_realm_name: trusted-artifact-signer
    keycloak_user_username: admin
    keycloak_user_password: password

    kafka_project: '{{ tpa_project }}'

    # TPA configuration
    tpa_project: trusted-profile-analyzer
    tpa_walker_secret: walker_secret
    tpa_helm_version: 0.1.2

    # Minio configuration
    minio_stateful: true
    minio_project: '{{ tpa_project }}'
    minio_key: minio
    minio_secret: minio123
    minio_region: eu-west-1
    minio_storage_size: 10Gi

    # Developer Hub Configuration
    rhdh_project: rhdh
    rhdh_keycloak_realm: rhdh
    rhdh_keycloak_client_id: rhdh
    rhdh_keycloak_client_secret: 9IAuKgbRcEUTU4mjeUUTY25P6IKo0B6L
    rhdh_sa_name: local-cluster
    rhdh_secret_name: secrets-rhdh
    rhdh_cm_name: app-config-rhdh
    rhdh_ns: rhdh
    rhdh_template_urls:
      - https://github.com/GcBackstageDemos/tssc-sample-templates/blob/my-version/all.yaml
      - https://github.com/GcBackstageDemos/trusted-application-pipeline-templates/blob/my-version/showcase-templates.yaml

    gitops_project: rhtap

    # pipeline
    pipeline_project: demo-tap-pipeline

    # Devspaces Configuration
    devspaces_enabled: true
    acs_enabled: false

  tasks:
    - name: Check Required Parameters
      ansible.builtin.fail:
        msg: "This play requires 'server' and 'token' to be defined"
      when:
        - (server is not defined) or (token is not defined) or (server is none) or (token is none)
      ignore_errors: false

    - name: Set domain
      ansible.builtin.set_fact:
        domain: "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Set Subdomain
      ansible.builtin.set_fact:
        route_subdomain: "apps.{{ domain }}"

    - name: Include Keycloak
      ansible.builtin.include_role:
        name: keycloak

    - name: Include ACS
      ansible.builtin.include_role:
        name: acs
      when: acs_enabled | bool

    - name: Include Tekton
      ansible.builtin.include_role:
        name: tekton

    - name: Include ArgoCD
      ansible.builtin.include_role:
        name: argocd

    - name: Include TAS
      ansible.builtin.include_role:
        name: tas

    - name: Include TPA
      ansible.builtin.include_role:
        name: tpa

    - name: Include RHDH
      ansible.builtin.include_role:
        name: devhub

    - name: Include DevSpaces
      ansible.builtin.include_role:
        name: devspaces
      when: devspaces_enabled | bool
