- name: Delete OpenShift GitOps Subscription
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: absent
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: openshift-gitops-operator
        namespace: openshift-operators
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: openshift-gitops-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
